apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: iot-gateway
    namespace: iot
spec:
    replicas: 1
    selector:
      matchLabels:
        app: iot-gateway
        tier: backend
        release: k8s-1.0
    template:
      metadata:
        labels:
          app: iot-gateway
          tier: backend
          release: k8s-1.0
      spec:
          containers:
          - name: iot-gateway
            image: reg.ops.com/iot2/iot-gateway:1550470503
            imagePullPolicy: IfNotPresent
            args: ["dev"]
            resources:
              requests:
                memory: "512Mi"
                cpu: "512m"
              limits:
                memory: "1024Mi"
                cpu: "1024m"
            ports:
            - name: iot-gateway
              containerPort: 8097

---
apiVersion: v1
kind: Service
metadata:
  name: iot-gateway-service
  namespace: iot
spec:
  selector:
    app: iot-gateway
    tier: backend
    release: k8s-1.0
  clusterIP: 10.254.40.34
  type: NodePort
  ports:
  - port: 8097
    targetPort: 8097
    nodePort: 30002
