apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: iot-turbine
    namespace: iot
spec:
    replicas: 1
    selector:
      matchLabels:
        app: iot-turbine
        tier: backend
        release: k8s-1.0
    template:
      metadata:
        labels:
          app: iot-turbine
          tier: backend
          release: k8s-1.0
      spec:
          containers:
          - name: iot-turbine
            image: reg.ops.com/iot2/iot-turbine:1550470503
            imagePullPolicy: IfNotPresent
            args: ["dev"]
            resources:
              requests:
                memory: "512Mi"
                cpu: "512m"
              limits:
                memory: "1024Mi"
                cpu: "1024m"
            ports:
            - name: iot-turbine
              containerPort: 8080

