---
- hosts: '{{ host }}'
  gather_facts: False
  tasks:
  - name: Deploy {{ app }} on {{ host  }}
    debug: msg="Deploy {{ app }} on {{ host  }}"
  - name: Register app 
    command: echo {{ app }}
    register: appname
    ignore_errors: True
  - name: Judge docker exists
    shell: docker ps -a | grep {{ app }} | awk '{print $NF}'
    register: DOCKER
    ignore_errors: True
  - name: Get docker image from harbor
    command: docker pull {{ url }}/iot2/{{ app }}:{{ time }}
  - name: Stop docker
    command: docker stop {{ app }}
    when: DOCKER.stdout != ''
  - name: Clear docker
    shell: docker rm -f {{ app }}
    when: DOCKER.stdout != ''
  - name: Start docker
    command: docker run -d --restart=always --name={{ app }} --net=host {{ url }}/iot2/{{ app }}:{{ time }} {{ env }}
  - name: wait 20 seconds
    shell: sleep 20
    when: appname.stdout in ["iot-registe","iot-config","huayun-common-eureka","huayun-common-config"]
