---
- hosts: "{{ host }}"
  gather_facts: False
  tasks:
    - name: Deploy {{ app }} on {{ host  }}
      debug: msg="Deploy {{ app }} on {{ host  }}"
    - name: Register app
      command: echo {{ app }}
      register: appname
      ignore_errors: True
    - name: Register env
      command: echo {{ env }}
      register: environ
      ignore_errors: True
    - name: Register project
      command: echo {{ project }}
      register: proj
      ignore_errors: True
    - name: Create a package dir
      file:
        path: /ddhome/packages
        state: directory
        recurse: yes
    - name: Get jar from {{ url }}
      get_url:
        url: "{{ url }}/{{ project }}/{{ version }}/BE/{{ env }}/{{ time }}/{{ app }}-zjhw.jar"
        dest: /ddhome/packages/{{ app }}.jar
        mode: 0740
        force: yes
    - name: Get bin from {{ url }}
      get_url:
        url: "{{ url }}/{{ project }}/{{ version }}/BIN/{{ env }}/{{ time }}/{{ app }}.tar.gz"
        dest: /ddhome/packages/{{ app }}.tar.gz
        mode: 0740
        force: yes
      when: appname.stdout in ["huayun-lab-report","huayun-lab-auth","huayun-lab-data"]
    - name: Create a running dir
      file:
        path: /ddhome/project/{{ project }}/{{ version }}/server/{{ app }}
        state: directory
        recurse: yes
    - name: Copy package to running dir
      shell: cp -f /ddhome/packages/{{ app }}.jar /ddhome/project/{{ project }}/{{ version }}/server/{{ app }}
    - name: Copy startup script to running dir
      template:
        src: ../templates/startup-iot.j2
        dest: /ddhome/project/{{ project }}/{{ version }}/server/{{ app }}/startup.sh
        mode: 0740
      when: proj.stdout == "iot" and environ.stdout not in ["prod"]
    - name: Copy startup script to running dir
      template:
        src: ../templates/startup-bigdata.j2
        dest: /ddhome/project/{{ project }}/{{ version }}/server/{{ app }}/startup.sh
        mode: 0740
      when: proj.stdout == "bigdata" and environ.stdout not in ["prod", "pre"]
    - name: Copy startup script to running dir
      template:
        src: ../templates/startup-prod.j2
        dest: /ddhome/project/{{ project }}/{{ version }}/server/{{ app }}/startup.sh
        mode: 0740
      when: environ.stdout in ["prod"]
    - name: Copy startup script to running dir
      template:
        src: ../templates/startup.j2
        dest: /ddhome/project/{{ project }}/{{ version }}/server/{{ app }}/startup.sh
        mode: 0740
      when: proj.stdout in ["arch"]
    - name: Clear bin script
      shell: rm -rf /ddhome/project/{{ project }}/{{ version }}/server/{{ app }}/bin/
      when: appname.stdout in ["huayun-lab-report","huayun-lab-auth", "huayun-lab-data"]
    - name: Copy bin script to running dir
      shell: tar xf /ddhome/packages/{{ app }}.tar.gz -C /ddhome/project/{{ project }}/{{ version }}/server/{{ app }}
      when: appname.stdout in ["huayun-lab-report","huayun-lab-auth", "huayun-lab-data"]
    - name: Stop Service
      shell: cd /ddhome/project/{{ project }}/{{ version }}/server/{{ app }};./startup.sh stop
    - name: wait 10 seconds
      shell: sleep 10
      when: appname.stdout in ["iot-registe","iot-config","huayun-common-eureka","huayun-common-config"]
    - name: Start Service
      shell: export BUILD_ID=DONTKILLME;cd /ddhome/project/{{ project }}/{{ version }}/server/{{ app }};./startup.sh start {{ env }}
    - name: wait 20 seconds
      shell: sleep 20
      when: appname.stdout in ["iot-registe","iot-config","huayun-common-eureka","huayun-common-config"]
