---
- hosts: '{{ host }}'
  gather_facts: False
  tasks:
  - name: Deploy {{ app }} on {{ host  }}
    debug: msg="Deploy  {{ app }} on {{ host  }}"
  - name: Judge
    shell: echo {{ first }}
    register: times
    ignore_errors: True
  - name: Create a package dir
    file: 
      path: /ddhome/packages 
      state: directory
      recurse: yes
  - name: Get package from {{ url }}
    get_url:
      url: "{{ url }}/{{ project }}/{{ version }}/FE/{{ env }}/{{ time }}/{{ app }}.tar.gz"
      dest: /ddhome/packages/
      mode: 0740
      force: yes 
  - name: Create a dir
    file:
      path: /ddhome/project/{{ project }}/{{ version }}/{{ dir }}
      state: directory
      recurse: yes
  - name: Clear dest dir
    shell: rm -rf /ddhome/project/{{ project }}/{{ version }}/{{ dir }}/*
  - name: Copy package to  dir
    shell: tar xf /ddhome/packages/{{ app }}.tar.gz -C /ddhome/project/{{ project }}/{{ version }}/{{ dir }}/
  - name: First deploy
    shell: export NODE_ENV={{ env }};cd /ddhome/project/{{ project }}/{{ version }}/{{ dir }}/; pm2 start ./bin/www --name {{ node }}
    when: times.stdout == "first"
  - name: Reload deploy
    shell: export NODE_ENV={{ env }};cd /ddhome/project/{{ project }}/{{ version }}/{{ dir }}/; pm2 reload {{ node }}
    when: times.stdout != "first"