---
- hosts: '{{ host }}'
  gather_facts: False
  tasks:
  - name: Deploy {{ app }} on {{ host  }}
    debug: msg="Deploy {{ app }} on {{ host  }}"
  - name: Register env 
    command: echo {{ env }}
    register: envir
    ignore_errors: True
  - name: Create a package dir
    file: 
      path: /ddhome/packages 
      state: directory
      recurse: yes
  - name: Add a group
    group:
      name: nginx
      state: present
  - name: Add a user
    user:
      name: nginx
      group: nginx
  - name: Get package from {{ url }}
    get_url:
      url: "{{ url }}/{{ project }}/{{ version }}/FE/{{ env }}/{{ time }}/{{ app }}.tar.gz"
      dest: /ddhome/packages/
      mode: 0740                                                                                                                 
      force: yes
  - name: Create a dir on {{ env }}
    file:
      path: /ddhome/project/{{ project }}/{{ version }}/web/{{ env }}/{{ dir }}
      state: directory
      recurse: yes
      owner: nginx
    when: envir.stdout != "prod"
  - name: Create a dir on prod
    file:
      path: /ddhome/project/{{ project }}/{{ version }}/web/{{ dir }}
      state: directory
      recurse: yes
      owner: nginx
    when: envir.stdout == "prod"
  - name: Clear dest dir on {{ env }}
    shell: rm -rf /ddhome/project/{{ project }}/{{ version }}/web/{{ env }}/{{ dir }}/*
    when: envir.stdout != "prod"
  - name: Clear dest dir on prod
    shell: rm -rf /ddhome/project/{{ project }}/{{ version }}/web/{{ dir }}/*
    when: envir.stdout == "prod"
  - name: Copy package to  dir on {{ env }}
    shell: tar xf /ddhome/packages/{{ app }}.tar.gz -C /ddhome/project/{{ project }}/{{ version }}/web/{{ env }}/{{ dir }}/
    when: envir.stdout != "prod"
  - name: Copy package to  dir on prod
    shell: tar xf /ddhome/packages/{{ app }}.tar.gz -C /ddhome/project/{{ project }}/{{ version }}/web/{{ dir }}/
    when: envir.stdout == "prod"
  - name: Chown user on {{ env }}
    shell: chown -R nginx.nginx /ddhome/project/{{ project }}/{{ version }}/web/{{ env }}/{{ dir }}/
    when: envir.stdout != "prod"
  - name: Chown user on prod
    shell: chown -R nginx.nginx /ddhome/project/{{ project }}/{{ version }}/web/{{ dir }}/
    when: envir.stdout == "prod"
